# Generated by Django 5.2.14 on 2026-05-22 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('groom_name', models.CharField(max_length=50)),
                ('bride_name', models.CharField(max_length=50)),
                ('wedding_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('venue2', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('groom_phone', models.CharField(blank=True, max_length=20)),
                ('bride_phone', models.CharField(blank=True, max_length=20)),
                ('groom_account', models.CharField(blank=True, max_length=100)),
                ('bride_account', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wedding/cover/')),
                ('photo_orientation', models.CharField(choices=[('landscape', '가로형'), ('portrait', '세로형')], default='landscape', max_length=10)),
                ('gallery1', models.ImageField(blank=True, null=True, upload_to='wedding/gallery/')),
                ('gallery2', models.ImageField(blank=True, null=True, upload_to='wedding/gallery/')),
                ('gallery3', models.ImageField(blank=True, null=True, upload_to='wedding/gallery/')),
                ('gallery4', models.ImageField(blank=True, null=True, upload_to='wedding/gallery/')),
                ('gallery5', models.ImageField(blank=True, null=True, upload_to='wedding/gallery/')),
                ('gallery6', models.ImageField(blank=True, null=True, upload_to='wedding/gallery/')),
                ('gallery7', models.ImageField(blank=True, null=True, upload_to='wedding/gallery/')),
                ('gallery8', models.ImageField(blank=True, null=True, upload_to='wedding/gallery/')),
                ('theme', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('romantic', 'Romantic')], default='classic', max_length=10)),
                ('map_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbooks', to='weddings.wedding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
